fn main() -> Result<(), Box<dyn std::error::Error>> {
    linker_be_nice()?;
    println!("cargo:rustc-link-arg=-Tlinkall.x");

    // Rebuild if our static GTFS data changes.
    println!("cargo:rerun-if-changed=docs/trips.csv");

    // Rebuild if protobuf definitions change.
    println!("cargo:rerun-if-changed=proto/state.proto");
    println!("cargo:rerun-if-changed=proto/com/google/transit/realtime/gtfs-realtime.proto");
    println!("cargo:rerun-if-changed=proto/com/google/transit/realtime/gtfs-realtime-NYCT.proto");
    println!(
        "cargo:rerun-if-changed=proto/com/google/transit/realtime/gtfs-realtime-time-range.proto"
    );

    let (protoc_bin, _) = protoc_prebuilt::init("22.0")
        .map_err(|e| format!("Failed to initialize protoc prebuilt: {}", e))?;
    let mut config = prost_build::Config::new();
    config.btree_map(&["."]);
    config.protoc_executable(protoc_bin);
    config.type_attribute(".", "#[derive(serde::Serialize,serde::Deserialize)]");
    config.compile_protos(
        &[
            "proto/com/google/transit/realtime/gtfs-realtime.proto",
            "proto/com/google/transit/realtime/gtfs-realtime-NYCT.proto",
            "proto/com/google/transit/realtime/gtfs-realtime-time-range.proto",
            "proto/state.proto",
        ],
        &["proto/"],
    )?;

    generate_gtfs_trip_headsign_lookup()?;
    Ok(())
}

fn generate_gtfs_trip_headsign_lookup() -> Result<(), Box<dyn std::error::Error>> {
    use std::{collections::BTreeMap, fs, io::Write, path::PathBuf};

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let trips_csv_path = manifest_dir.join("docs/trips.csv");
    let trips_csv = fs::read_to_string(&trips_csv_path)?;

    // trip_id (and also normalized short trip_id) -> headsign counts
    let mut trips: BTreeMap<String, BTreeMap<String, u32>> = BTreeMap::new();

    for (idx, line) in trips_csv.lines().enumerate() {
        if idx == 0 {
            // header
            continue;
        }
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        // route_id,trip_id,service_id,trip_headsign,direction_id,shape_id
        let mut parts = line.split(',');
        let _route_id = parts.next();
        let trip_id = parts.next();
        let _service_id = parts.next();
        let trip_headsign = parts.next();

        let (Some(trip_id), Some(trip_headsign)) = (trip_id, trip_headsign) else {
            continue;
        };

        // Keep the first entry; duplicates (if any) should agree.
        insert_trip_headsign(&mut trips, trip_id, trip_headsign);

        // Also insert a normalized key so realtime trip_ids like "141250_L..N"
        // can resolve when the static GTFS uses prefixed/provider-form trip_ids.
        if let Some(short_trip_id) = extract_short_trip_id(trip_id) {
            insert_trip_headsign(&mut trips, &short_trip_id, trip_headsign);
        }
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    let out_path = out_dir.join("gtfs_trips.rs");
    let mut f = fs::File::create(&out_path)?;

    writeln!(
        f,
        "// @generated by build.rs from docs/trips.csv\n\
        // trip_id -> trip_headsign lookup\n"
    )?;

    writeln!(
        f,
        "pub(crate) fn headsign_for_trip_id(trip_id: &str) -> Option<&'static str> {{"
    )?;
    writeln!(f, "    const TRIPS: &[(&str, &str)] = &[")?;

    for (trip_id, headsign_counts) in &trips {
        let headsign = pick_most_common_headsign(headsign_counts);
        writeln!(f, "        ({:?}, {:?}),", trip_id, headsign)?;
    }

    writeln!(f, "    ];")?;
    writeln!(
        f,
        "    match TRIPS.binary_search_by(|entry| entry.0.cmp(trip_id)) {{\n\
            Ok(idx) => Some(TRIPS[idx].1),\n\
            Err(_) => None,\n\
        }}"
    )?;
    writeln!(f, "}}")?;

    Ok(())
}

fn insert_trip_headsign(
    map: &mut std::collections::BTreeMap<String, std::collections::BTreeMap<String, u32>>,
    trip_id: &str,
    headsign: &str,
) {
    let counts = map
        .entry(trip_id.to_string())
        .or_insert_with(std::collections::BTreeMap::new);
    *counts.entry(headsign.to_string()).or_insert(0) += 1;
}

fn pick_most_common_headsign(counts: &std::collections::BTreeMap<String, u32>) -> &str {
    // Deterministic: pick highest count, and on ties pick lexicographically smallest.
    counts
        .iter()
        .max_by(|(a_name, a_count), (b_name, b_count)| {
            a_count.cmp(b_count).then_with(|| b_name.cmp(a_name))
        })
        .map(|(name, _count)| name.as_str())
        .unwrap_or("")
}

fn extract_short_trip_id(full_trip_id: &str) -> Option<String> {
    // Examples:
    // - BFA25GEN-L027-Sunday-00_141250_L..N01R  -> 141250_L..N
    // - AFA25GEN-1038-Sunday-00_000600_1..S03R  -> 000600_1..S
    // - 141250_L..N                            -> 141250_L..N

    let bytes = full_trip_id.as_bytes();
    if bytes.len() < 7 {
        return None;
    }

    // Find the first "HHMMSS_" token (6 digits + '_')
    let mut start = None;
    for i in 0..=bytes.len().saturating_sub(7) {
        if bytes[i + 6] != b'_' {
            continue;
        }
        if bytes[i..i + 6].iter().all(|b| b.is_ascii_digit()) {
            start = Some(i);
            break;
        }
    }

    let start = start.unwrap_or(0);
    let mut short = full_trip_id[start..].to_string();

    // Strip provider pattern suffix like "01R"/"03R" when it follows a direction letter.
    // This matches how realtime often omits the suffix (e.g. "...L..N").
    if short.len() >= 4 {
        let sbytes = short.as_bytes();
        let end = sbytes.len();
        let dir = sbytes[end - 4];
        let d1 = sbytes[end - 3];
        let d2 = sbytes[end - 2];
        let letter = sbytes[end - 1];

        let is_dir = matches!(dir, b'N' | b'S' | b'E' | b'W');
        let is_digits = d1.is_ascii_digit() && d2.is_ascii_digit();
        let is_letter = (letter as char).is_ascii_uppercase();
        if is_dir && is_digits && is_letter {
            short.truncate(short.len() - 3);
        }
    }

    Some(short)
}

fn linker_be_nice() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "💡 Did you forget the `esp-alloc` dependency or didn't enable the `compat` feature on it?"
                    );
                    eprintln!();
                }
                _ => (),
            },
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe()?.display()
    );
    Ok(())
}
